version: '3.8'

x-environment: &default-environment
  DATABASE_URL: postgres://user:password@postgres:5432/database
  SECRET_KEY: secret # best to run openssl rand -hex 32
  PORT: 8000 # If changing, change the web service port too
  EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port
  GLITCHTIP_DOMAIN: http://localhost:8000 # Updated for local deployment
  DEFAULT_FROM_EMAIL: email@example.com # Change this to your email
  CELERY_WORKER_AUTOSCALE: "1,3" # Scale between 1 and 3

services:
  postgres:
    image: postgres:15.4 # Specific version for stability
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bd-network

  mongodb:
    image: mongo:6.0.8 # Specific version for stability
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bd-network

  redis:
    image: redis:7.0.12 # Specific version for stability
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bd-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5 # Specific version for stability
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: database
      DB_USER: user
      DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - bd-network
    command: start-dev

  minio:
    image: minio/minio:RELEASE.2023-07-07T07-07-39Z # Specific version for stability
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - bd-network

  web-glitchtip:
    image: glitchtip/glitchtip:v3.0.3 # Specific version for stability
    ports:
      - "8000:8000"
    environment: *default-environment
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - uploads-glitchtip:/code/uploads
    networks:
      - bd-network

  backend-glitchtip:
    image: glitchtip/glitchtip:v3.0.3 # Same version as web-glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - postgres
      - redis
      - minio
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads-glitchtip:/code/uploads
    networks:
      - bd-network

networks:
  bd-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  mongo-data:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local
  uploads-glitchtip:
    driver: local